"""Add_ML_Fields

Revision ID: ddb450f421d3
Revises: f0f77b0c3c51
Create Date: 2026-01-02 08:16:40.764061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddb450f421d3'
down_revision: Union[str, None] = 'f0f77b0c3c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('alert_type', sa.String(), nullable=False))
    op.add_column('alerts', sa.Column('anomaly_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'anomaly_score')
    op.drop_column('alerts', 'alert_type')
    # ### end Alembic commands ###
